const batFrames=['assets/bats/bat-1.svg','assets/bats/bat-2.svg','assets/bats/bat-3.svg'];
const bat=document.querySelector('#flyingBat');let frame=0;
const batTimer=setInterval(()=>{bat.src=batFrames[frame++%batFrames.length]},120);
setTimeout(()=>{bat.classList.add('fly');clearInterval(batTimer)},70);
const dialog=document.querySelector('#cameraDialog'),openCamera=document.querySelector('#openCamera'),closeCamera=document.querySelector('#closeCamera'),video=document.querySelector('#cameraFeed'),status=document.querySelector('#cameraStatus'),seal=document.querySelector('#detectedSeal'),enter=document.querySelector('#enterPortal'),canvas=document.querySelector('#visionCanvas'),reference=document.querySelector('#lampReference');
let stream=null,scanTimer=null,targetSignature=null,stableHits=0;
function signature(source,width,height){const c=document.createElement('canvas');c.width=32;c.height=40;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(source,0,0,width,height,0,0,32,40);const pixels=x.getImageData(0,0,32,40).data,values=[];for(let i=0;i<pixels.length;i+=4)values.push(.2126*pixels[i]+.7152*pixels[i+1]+.0722*pixels[i+2]);const avg=values.reduce((a,b)=>a+b,0)/values.length;const variance=Math.sqrt(values.reduce((a,b)=>a+(b-avg)**2,0)/values.length)||1;return values.map(v=>(v-avg)/variance)}
function similarity(a,b){return a.reduce((sum,value,index)=>sum+Math.abs(value-b[index]),0)/a.length}
reference.addEventListener('load',()=>{targetSignature=signature(reference,reference.naturalWidth,reference.naturalHeight)});
async function startCamera(){dialog.showModal();status.textContent='Pedindo permissão para a câmera…';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment',width:{ideal:1280},height:{ideal:720}},audio:false});video.srcObject=stream;await video.play();status.textContent='Aponte para a frente iluminada da luminária.';scanTimer=setInterval(scanFrame,250)}catch(error){status.textContent='Não foi possível abrir a câmera. Verifique a permissão do navegador.'}}
function scanFrame(){if(!targetSignature||!video.videoWidth)return;const vw=video.videoWidth,vh=video.videoHeight,ratio=204/248;let sw=Math.min(vw,vh*ratio),sh=sw/ratio;if(sh>vh){sh=vh;sw=sh*ratio}const sx=(vw-sw)/2,sy=(vh-sh)/2;canvas.width=204;canvas.height=248;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,sx,sy,sw,sh,0,0,204,248);const score=similarity(signature(canvas,204,248),targetSignature);if(score<.68){stableHits++}else{stableHits=0}if(stableHits>=3)recognize()}
function recognize(){clearInterval(scanTimer);scanTimer=null;seal.classList.add('show');enter.disabled=false;status.textContent='A luminária encontrou o portal.'}
function stopCamera(){clearInterval(scanTimer);scanTimer=null;stableHits=0;if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}video.srcObject=null;seal.classList.remove('show');enter.disabled=true}
openCamera.addEventListener('click',startCamera);closeCamera.addEventListener('click',()=>{stopCamera();dialog.close()});dialog.addEventListener('close',stopCamera);enter.addEventListener('click',()=>{status.textContent='O portal está pronto — a próxima página entrará aqui.'});
